name: Build and Publish

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY_NAME: ghcr.io/zinrai
  IMAGE_NAME: hello_sample
  CACHE_PATH: /tmp/.buildx-cache-hello_sample

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-${{ env.CACHE_PATH }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_PATH }}

      - name: Create Docker tag
        run: |
          TAG=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ env.DOCKER_TAG }}
          push: true
          file: Dockerfile
          cache-from: type=local,src=${{ env.CACHE_PATH }}
          cache-to: type=local,dest=${{ env.CACHE_PATH }}-new,mode=max

      - name: Move cache
        run: |
          rm -rf ${{ env.CACHE_PATH }}
          mv ${{ env.CACHE_PATH }}-new ${{ env.CACHE_PATH }}
